---
- name: inject key-values into consul
  consul_kv:
    key: "{{ item.key }}"
    value: "{{ item.value | to_json }}"
  with_items: "{{ webgate_kv }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
  when: webgate_kv is defined
