---
- name: inject key-values into consul
  consul_kv:
    key: "{{ item.key }}"
    value: "{{ item.value | to_json }}"
  with_items: "{{ webgate_kv }}"
  vars:
    ansible_python_interpreter: /root/consul/bin/python
  when: webgate_kv is defined

- name: Patch nginx conf for redirect IDM
  lineinfile:
    path: /etc/nginx/conf.d/default.conf
    insertafter: "    proxy_pass http://idm80http/;"
    line: "    proxy_redirect http://idm.admin-gate.procube-demo.jp/infoscoop/ https://idm.admin-gate.procube-demo.jp/infoscoop/;"
  notify: restart nginx
