---
- name: Change password for certificate user
  arista.eos.eos_user:
    name: '{{ certificationUser }}'
    configured_password: '{{ certificationPassword }}'
    update_password: always
    state: present
- name: write memory
  arista.eos.eos_command:
    commands: write memory
