---
- name: Provisioning to user account.
  hosts: connections
  gather_facts: false
  serial: 1
  vars:
    ansible_connection: local
    ansible_python_interpreter: /root/prov/bin/python
    username: guacadmin
    password: guacadmin

  tasks:
  - name: Register connection.