---
- name: Provisioning to user account.
  hosts: connections
  gather_facts: false
  serial: 1
  vars:
    ansible_host: "{{ hostname }}"
    ansible_python_interpreter: /root/prov/bin/python
    username: guacadmin
    password: guacadmin
    cs_obj: "{{ hostvars[connectionSpecification] }}"
    ansible_user: "{{ cs_obj.ansibleID }}"
    ansible_password: "{{ cs_obj.ansiblePassword }}"

  tasks:
  - name: Change password.
    include_tasks:
      file: "connection/changePassword/{{ cs_obj.osType }}.yml"
    when: cs_obj[loop_protocol] and (cs_obj[loop_protocol ~ 'ID'] != hostvars[hostname][loop_protocol ~ 'ID'] | default('') or cs_obj[loop_protocol ~ 'Password'] != lookup('vars', loop_protocol ~ 'Password') | default(''))
    loop:
      - ssh
      - rdp
      - telnet
      - vnc
    loop_control:
      loop_var: loop_protocol
  - name: Register connection.
    include_tasks:
      file: "connection/register/{{ loop_protocol }}.yml"
    when: cs_obj[loop_protocol] and (cs_obj[loop_protocol ~ 'ID'] != hostvars[hostname][loop_protocol ~ 'ID'] | default('') or cs_obj[loop_protocol ~ 'Password'] != lookup('vars', loop_protocol ~ 'Password') | default(''))
    loop:
      - ssh
      - rdp
      - telnet
      - vnc
    loop_control:
      loop_var: loop_protocol
