---
- name: Provisioning to change machines password
  hosts: machines
  gather_facts: false
  serial: 1
  vars:
    ansible_host: '{{ hostname }}'
    ansible_user: idm
    ansible_ssh_pass: qjStae49xPgh3wT1A
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arista.eos.eos
    ansible_become: yes
    ansible_become_method: enable
    username: guacadmin
    password: guacadmin

  tasks:
#  - name: Change password for certificate User.
#    include_tasks:
#      file: machine/change-password.yml
  - name: Register connection.
    include_tasks:
      file: machine/register-connection.yml 
    loop: "{{ insideConnectionsObject}}"
    loop_control:
      loop_var: connection
