---
- name: Provisioning to change machines password
  hosts: machines
  gather_facts: false
  serial: 1
  vars:
    ansible_host: '{{ hostname }}'
    ansible_user: '{{ certificationUser }}'
    ansible_ssh_pass: '{{ certificationPassword }}'
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: arista.eos.eos
    ansible_become: yes
    ansible_become_method: enable

  tasks:
  - name: message
    debug:
      msg: "Provisioning to change machines password"
  - name: Change password for certificate user
    arista.eos.eos_user:
      username: '{{ certificationUser }}'
      configured_password: '{{ certificationPassword }}'
      update_password: always
      state: present
