---
- import_role:
    name: install-docker-plugin
  when: inventory_hostname in groups['hives']
- import_role:
    name: pull-docker-images
  when: inventory_hostname in groups['hives']
- import_role:
    name: create-docker-volumes
  when: inventory_hostname in groups['hives']
