---
- import_role:
    name: install-docker-plugin
  when: inventory_hostname in groups['hives']
- import_role:
    name: pull-docker-images
  when: inventory_hostname in groups['hives']
- import_role:
    name: make-directories
  when: inventory_hostname in groups['first_hive']
