---
plugin: hive_services
services:
  guacamole:
    image:
      from: procube/guacamole
      roles:
      - guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME: /opt/guacamole/
    volumes:
    - source: guacamole-drives
      target: /var/lib/guacamole/drives
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    - source: recordings
      target: /var/lib/guacamole/recordings
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    user: root
    labels:
      webgate:
        authentication: saml
        proxies:
        - target_port: 8080
          pathPattern: /guacamole
          useWebSocket: true 
    endpoint_mode: dnsrr
  guacd:
    image: guacamole/guacd
    volumes:
    - source: guacamole-drives
      target: /var/lib/guacamole/drives
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    - source: guacamole-recordings
      target: /var/lib/guacamole/recordings
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    endpoint_mode: dnsrr
  postgres:
    image:
      from: postgres:15.2-alpine
      roles:
      - python-aptk
      - guacamole-initdb
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    volumes:
    - source: guacamole-db
      target: /var/lib/postgresql/data
      type: volume
      drbd:
        fstype: xfs
        size: 5G
    endpoint_mode: dnsrr
  chrome:
    image: procube/node-chrome
    volumes:
    - source: guacamole-chrome
      target: /dev/shm
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    environment:
      - USERNAME: guacamole_user
      - PASSWORD: tNpaYnkuPh6z
  file-server:
    image: procube/file-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    labels:
      published_name: guacamole
      webgate:
        authentication: saml
        proxies:
        - target_port: 8081
          pathPattern: /file-server
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: files_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
