---
plugin: hive_services
services:
  guacamole:
    image:
      from: procube/guacamole
      # from: nigauri/guacamole
      roles:
      - guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME: /opt/guacamole/
      RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings
      HEADER_ENABLED: 'true'
      LOGBACK_LEVEL: debug
    volumes:
    - source: guacamole-drives
      target: /var/lib/guacamole/drives
      type: volume
    - source: guacamole-recordings
      target: /var/lib/guacamole/recordings
      type: volume
    user: root
    labels:
      published_name: guacamole
      HIVE_MARK: guacamole
      webgate:
        authentication: saml
        proxies:
        - target_port: 8080
          pathPattern: /guacamole
          useWebSocket: true
    endpoint_mode: dnsrr
  guacd:
    image: procube/guacd
    volumes:
    - source: guacamole-drives
      target: /var/lib/guacamole/drives
      type: volume
      drbd:
        fstype: xfs
        size: 300M
    - source: guacamole-recordings
      target: /var/lib/guacamole/recordings
      type: volume
      drbd:
        fstype: xfs
        size: 20G
    endpoint_mode: dnsrr
    placement:
      constraints:
      - node.labels.guacamole == true
      - node.labels.repository != true
  postgres:
    image:
      from: postgres:15.2-alpine
      roles:
      - python-aptk
      - guacamole-initdb
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: 'ChooseYourOwnPasswordHere1234'
      POSTGRES_USER: guacamole_user
    volumes:
    - source: guacamole-db
      target: /var/lib/postgresql/data
      type: volume
      drbd:
        fstype: xfs
        size: 5G
    endpoint_mode: dnsrr
  file-server:
    image: procube/file-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: "mongodb://mongo:27017/files_db?authSource=admin"
    ports:
      - 4200:4200
    labels:
      webgate:
        authentication: saml
        proxies:
        - target_port: 4200
          maxBodySize: 500
  ftp-server:
    image: procube/ftp-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      PASV_IP: "192.168.0.4"
      PASV_PORT_MIN: "30000"
      PASV_PORT_MAX: "30003"
    ports:
      - "21:21"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
    placement:
      constraints:
        - node.hostname == s-hive0
  sftpserver:
    image: procube/sftp-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
    - '22:22'
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_DATABASE: files_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
  session-manager:
    image:
      from: python:alpine3.18
      roles:
      - hive-trust-ca
      - session-manager
      - hive-certificate
    entrypoint:
    - /docker-entrypoint.sh
    environment:
    - IMAGE_CHROME: "{{ groups['repository'] | intersect(groups[hive_stage]) | first }}:5000/image_chrome:latest"
    - WEBDAV_SERVER: "192.168.10.4"
    - WEBDAV_PORT: "8888"
    - WEBDAV_USERNAME: "user"
    - WEBDAV_PASSWORD: "test"
    - GUACAMOLE_URL: "http://guacamole:8080/guacamole"
    - GUACAMOLE_USERNAME: "{{ credentials.guacamole_username }}"
    - GUACAMOLE_PASSWORD: "{{ credentials.guacamole_password }}"
    - VNC_PORT: "5900"
    - VNC_PASSWORD: "{{ credentials.vnc_password }}"
  dummy-guacamole-for-vnc:
    image:
      from: node:18.18-alpine3.18
      roles:
      - python-aptk
      - dummy-guacamole-for-vnc
    command:
    - npm
    - start
  dummy-guacamole-for-rdp:
    image:
      from: node:18.18-alpine3.18
      roles:
      - python-aptk
      - dummy-guacamole-for-rdp
    command:
    - npm
    - start
  dummy-guacamole-for-ssh:
    image:
      from: node:18.18-alpine3.18
      roles:
      - python-aptk
      - dummy-guacamole-for-ssh
    command:
    - npm
    - start
  nginx:
    image: nginx:1.25.3
  apache:
    image:
      from: httpd:2.4
      roles:
      - python-aptk
      - apache
  webdav:
    image: bytemark/webdav
    ports:
      - 8888:80
    environment:
      AUTH_TYPE: Digest
      USERNAME: user
      PASSWORD: test
      ANONYMOUS_METHODS: ALL
    volumes:
    - source: /mnt/test
      target: /var/lib/dav/data
      type: bind
    placement:
      constraints:
      - node.hostname == p-hive0

  # chrome:
  #   image:
  #     from: procube/node-chrome
  #     roles:
  #     - node-chrome
  #   volumes:
  #   - source: /dev/shm
  #     target: /dev/shm
  #     type: bind
  #   environment:
  #     - USERNAME: demo@procube.jp
  #     - PASSWORD: EXPp7Od9
  #     - RULES: '["procube.info","backlog.jp","google.com"]'
  #     - WHITELIST: '["192.168.100.5","192.168.100.6","192.168.100.7"]'
