---
plugin: hive_services
services:
  guacamole:
    image:
      from: procube/guacamole:develop
      roles:
        - guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRES_USER: guacamole_user
      GUACAMOLE_HOME: /opt/guacamole/
      RECORDING_SEARCH_PATH: /var/lib/guacamole/recordings
      HEADER_ENABLED: "true"
      LOGBACK_LEVEL: debug
    volumes:
      - source: guacamole-drives
        target: /var/lib/guacamole/drives
        type: volume
      - source: guacamole-recordings
        target: /var/lib/guacamole/recordings
        type: volume
    user: root
    labels:
      published_name: guacamole
      HIVE_MARK: guacamole
      # webgate:
      #   authentication: saml
      #   proxies:
      #     - target_port: 8080
      #       pathPattern: /guacamole
      #       useWebSocket: true
    endpoint_mode: dnsrr
  guacd:
    image: procube/guacd
    volumes:
      - source: guacamole-drives
        target: /var/lib/guacamole/drives
        type: volume
        drbd:
          fstype: xfs
          size: 300M
      - source: guacamole-recordings
        target: /var/lib/guacamole/recordings
        type: volume
        drbd:
          fstype: xfs
          size: 20G
    endpoint_mode: dnsrr
    placement:
      constraints:
        - node.labels.guacamole == true
        - node.labels.repository != true
  guacamole-db:
    image:
      from: postgres:15.2-alpine
      roles:
        - python-aptk
        - guacamole-initdb
    environment:
      PGDATA: /var/lib/postgresql/data/guacamole
      POSTGRES_DB: guacamole_db
      POSTGRES_PASSWORD: "ChooseYourOwnPasswordHere1234"
      POSTGRES_USER: guacamole_user
    volumes:
      - source: guacamole-db
        target: /var/lib/postgresql/data
        type: volume
        drbd:
          fstype: xfs
          size: 5G
    endpoint_mode: dnsrr
    backup_scripts:
      - name: guacamole_db
        backup_command: pg_dump -U guacamole_user -c -C --if-exists guacamole_db | gzip > /root/today.sql.gz
        restore_command: psql -U guacamole_user guacamole_db -f /root/pg-terminate-backend.sql;  zcat /root/today.sql.gz | psql -U guacamole_user postgres
        backup_file: /root/today.sql.gz
        restore_file: /root/today.sql.gz
        ext: sql.gz
        cleanup_days_before: 3
  file-server:
    image: procube/file-server
    initialize_roles:
      - file-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: "mongodb://files-db:27017/files_db?authSource=admin"
      GUAC_URL: https://file-server.nsag-dev.procube-demo.jp/guacamole
      GUAC_API_URL: http://guacamole:8080/guacamole
      SESSION_MANAGER_URL: http://session-manager:80
      IDM_URL: https://idm.nsag-dev.procube-demo.jp
      WS_URL: wss://file-server.nsag-dev.procube-demo.jp
      LOGOUT_URL: https://file-server.nsag-dev.procube-demo.jp/Shibboleth.sso/Logout
      # APPBAR_LOGO_PATH: "icons/sakura-internet_logomark.png"
      # FAVICON_PATH: "icons/sakura-internet_favicon.ico"
    ports:
      - 4200:4200
    volumes:
      - source: fileserver-icons
        target: /usr/src/app/icons
        type: volume
        drbd:
          fstype: xfs
          size: 300M
    labels:
      published_name: file-server
      HIVE_MARK: file-server
      webgate:
        authentication: saml
        proxies:
          - target_port: 4200
            maxBodySize: 500
            pathPattern: /
            useWebSocket: "true"
          - target_port: 8080
            pathPattern: /guacamole
            setService: guacamole
            useWebSocket: true
  ftp-server:
    image: procube/ftp-server
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
      PASV_IP: "{{ '10.160.194.116' if hive_stage == 'production' else '192.168.0.4' }}"
      PASV_PORT_MIN: "30000"
      PASV_PORT_MAX: "30003"
    ports:
      - "21:21"
      - "30000:30000"
      - "30001:30001"
      - "30002:30002"
      - "30003:30003"
    labels:
      HIVE_VIP: "{{ '10.160.194.116' if hive_stage == 'production' else null }}"
    placement:
      constraints:
        - "{{ 'node.hostname == hive0' if hive_stage == 'production' else 'node.hostname == s-hive0' }}"
  # sftpserver:
  #   image: procube/sftp-server
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example
  #     SFTP_SERVER_PORT: "8822"
  #     DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
  #   ports:
  #     - "8822:8822"
  files-db:
    image:
      from: mongo
      roles:
        - python-aptk
        - fileserver-initdb
    environment:
      MONGO_INITDB_DATABASE: files_db
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - source: files-db
        target: /data/db
        type: volume
        drbd:
          fstype: xfs
          size: 20G
      - source: files-configdb
        target: /data/configdb
        type: volume
        drbd:
          fstype: xfs
          size: 2G
    backup_scripts:
      - name: files_db
        container: files-db
        backup_command: "mongodump --uri=mongodb://root:example@localhost:27017/files_db?authSource=admin --gzip --archive=/archive"
        backup_file: "/archive"
        restore_command: "mongorestore --uri=mongodb://root:example@localhost:27017/files_db?authSource=admin --db=files_db --gzip --archive=/archive --drop"
        restore_file: "/archive"
        cleanup_days_before: 3
  webdav-server:
    image: procube/webdav-server
    ports:
      - 2000:2000
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      DATABASE_URL: mongodb://files-db:27017/files_db?authSource=admin
      # WEBDAV_SERVER_PORT: 2000
      # WEBDAV_PUBLIC_VOLUME_USERNAME: public
    placement:
      constraints:
        - "{{ 'node.hostname == hive1' if hive_stage == 'production' else 'node.hostname == s-hive1' }}"
    labels:
      HIVE_VIP: "{{ '10.160.194.119' if hive_stage == 'production' else null }}"
  session-manager:
    image:
      from: python:alpine3.18
      roles:
        - hive-trust-ca
        - session-manager
        - hive-certificate
    entrypoint:
      - /docker-entrypoint.sh
    environment:
      - IMAGE_CHROME: "{{ groups['repository'] | intersect(groups[hive_stage]) | first }}:5000/image_chrome:latest"
      - WEBDAV_SERVER: "192.168.0.5"
      - WEBDAV_PORT: "2000"
      - WEBDAV_USERNAME: "user"
      - WEBDAV_PASSWORD: "test"
      - GUACAMOLE_URL: "http://guacamole:8080/guacamole"
      - GUACAMOLE_USERNAME: "guacadmin"
      - GUACAMOLE_PASSWORD: "guacadmin"
      - VNC_PORT: "5900"
      - VNC_PASSWORD: "secret"
  scep-server:
    image: 
      from: ghcr.io/procube-open/scep:0.0.9-rc.2
      roles:
        - python-aptk
        - scep-server
    environment:
      - SCEP_IDM_GET_URL: "http://idm:8090/IDManager/swConnectorGetIF"
      - SCEP_IDM_PUT_URL: "http://idm:8090/IDManager/swConnectorPutIF"
      - SCEP_IDM_USERS_URL: "http://idm:8090/IDManager/swConnectorGetIF"
      - SCEPCA_IDM_CRL_URL: "http://idm:8090/IDManager/"
    ports:
      - "13000:3000"
    volumes:
      - source: idm-depot
        target: /app/idm-depot
        type: volume
        drbd:
          fstype: xfs
          size: 300M
    labels:
      published_name: scep-server
      HIVE_MARK: scep-server
      webgate:
        authentication: saml
        proxies:
          - target_port: 3000
            pathPattern: /
  sw-listener:
    image: 
      from: ghcr.io/procube-open/socket-warp:1.1.6-rc.2
      roles: 
        - sw-listener
    ports:
      - "11443:11443/udp"
    environment:
      - SWL_CERT_PATH: "{{ swl_cert_path }}/server.crt"
      - SWL_KEY_PATH: "{{ swl_cert_path }}/server.key"
      - SWL_CA_PATH: "{{ swl_ca_path }}/ca.crt"
      - SCEP_SERVER_URL: "http://scep-server:3000/userObject"
    labels:
      published_name: sw-listener
      HIVE_MARK: sw-listener
      webgate:
        proxies:
          - target_port: 11443
            target_protocol: udp
            pathPattern: /