plugin: hive_inventory
name: admin-gate
stages:
  private:
    provider: prepared
    separate_repository: False
    cidr: 10.0.0.0/25
    ip_address_list:
    - 10.0.0.126
    root_password: test
  staging:
    provider: gcp
    cidr: 192.168.0.0/24
    instance_type: n1-standard-2
    region: asia-northeast2
    disk_size: 100
    mirrored_disk_size: 80
    repository_instance_type: n1-standard-2
    repository_disk_size: 150
  production:
    provider: aws
    cidr: 192.168.0.0/24
    region: ap-northeast-1
    disk_size: 100
    mirrored_disk_size: 80
    instance_type: t3.large
    repository_instance_type: t3.large
    repository_disk_size: 150
    subnets:
    - cidr: 192.168.0.0/26
      name: subnet-a
      available_zone: ap-northeast-1d
    - cidr: 192.168.0.64/26
      name: subnet-b
      available_zone: ap-northeast-1b
    - cidr: 192.168.0.128/26
      name: subnet-c
      available_zone: ap-northeast-1c
