plugin: hive_inventory
name: nsag-dev
stages:
  private:
    provider: vagrant
    separate_repository: False
    cidr: 192.168.208.0/24
    memory_size: 6000
    disk_size: 60
    mirrored_disk_size: 50
  staging:
    provider: gcp
    cidr: 192.168.0.0/24
    instance_type: n1-standard-2
    region: asia-northeast2
    disk_size: 100
    mirrored_disk_size: 80
    repository_instance_type: n1-standard-2
    repository_disk_size: 300
  production:
    provider: gcp
    cidr: 192.168.0.0/24
    instance_type: n1-standard-2
    region: asia-northeast2
    disk_size: 100
    mirrored_disk_size: 80
    repository_instance_type: n1-standard-2
    repository_disk_size: 300
