---
- name: Get connection specification.
  uri:
    url: "http://localhost:8090/IDManager/SystemConnectionSpecificationIF/{{ connectionSpecification }}"
    headers:
      HTTP_SYSTEMACCOUNT: "SYSTEM"
    method: GET
    validate_certs: false
    status_code: 200
  register: cs_obj

- name: Get token of REST API.
  uri:
    url: "http://guacamole:8080/guacamole/api/tokens"
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    method: POST
    body: 'username={{ username }}&password={{ password }}'
    validate_certs: false
    return_content: yes
    status_code: 200
  register: token

- name: Get Users.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/users"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
    method: GET
    validate_certs: false
    return_content: yes
    status_code: 200
  register: guacamole_users

- name: Get Connections.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/connections"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
    method: GET
    validate_certs: false
    return_content: yes
    status_code: 200
  register: guacamole_connections
- name: Set fact to target connection id.
  set_fact:
    connectionidssh: "{{ item.key }}"
  when: item.value.idmIdentifier == id and item.value.protocol == 'ssh'
  loop: "{{ guacamole_connections.json | dict2items }}"
  loop_control:
    label: "{{ item.key }}"

- name: Put connection.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/connections/{{ connectionidssh }}"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
      Content-Type: "application/json"
    method: PUT
    body_format: json
    body:
      name: "{{ hostname }}:{{ id }}-ssh"
      parentIdentifier: ROOT
      protocol: "ssh"
      idmIdentifier: "{{ id }}"
      parameters:
        port: "{{ cs_obj.json.sshPort | default('') }}"
        create-recording-path: "true"
        recording-path: "${HISTORY_PATH}/${HISTORY_UUID}"
        username: "{{ cs_obj.json.sshID }}"
        password: "{{ cs_obj.json.sshPassword }}"
        create-typescript-path: "true"
        typescript-path: "${HISTORY_PATH}/${HISTORY_UUID}"
        typescript-name: typescript
        hostname: "{{ hostname }}"
      attributes:
        remark: "{{ remark | default('') }}"
        max-connections: "0"
        max-connections-per-user: "0"
        weight: ""
        failover-only: ""
        guacd-port: ""
        guacd-encryption: ""
    validate_certs: false
    status_code: 204
  when: prov_operation != 'delete' and connectionidssh is defined

- name: Post connection.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/connections"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
      Content-Type: "application/json"
    method: POST
    body_format: json
    body:
      name: "{{ hostname }}:{{ id }}-ssh"
      parentIdentifier: ROOT
      protocol: "ssh"
      idmIdentifier: "{{ id }}"
      parameters:
        port: "{{ cs_obj.json.sshPort | default('') }}"
        create-recording-path: "true"
        recording-path: "${HISTORY_PATH}/${HISTORY_UUID}"
        username: "{{ cs_obj.json.sshID }}"
        password: "{{ cs_obj.json.sshPassword }}"
        create-typescript-path: "true"
        typescript-path: "${HISTORY_PATH}/${HISTORY_UUID}"
        typescript-name: typescript
        hostname: "{{ hostname }}"
      attributes:
        remark: "{{ remark | default('') }}"
        max-connections: "0"
        max-connections-per-user: "0"
        weight: ""
        failover-only: ""
        guacd-port: ""
        guacd-encryption: ""
    validate_certs: false
    return_content: yes
    status_code: 200
  when: connectionidssh is not defined
  register: new_connection

- name: Delete connection.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/connections/{{ connectionidssh }}"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
    method: DELETE
    validate_certs: false
    status_code: 204
  when: prov_operation == 'delete' and connectionidssh is defined

- name: Register connection permission.
  uri:
    url: "http://guacamole:8080/guacamole/api/session/data/postgresql/users/{{ item | regex_replace('@', '%40') }}/permissions"
    headers:
      Guacamole-Token: "{{ token.json.authToken }}"
      Content-Type: "application/json"
    method: PATCH
    body_format: json
    body: "{{ [{'op': 'add', 'path': '/connectionPermissions/' ~ new_connection.json.identifier, 'value': 'READ'}] }}"
    validate_certs: false
    status_code: 204
  loop: "{{ guacamole_users.json.keys() }}"
  when: connectionidssh is not defined and new_connection.json is defined
