- hosts: ae0000-fw001
  gather_facts: false
  collections:
  - cisco.asa

  tasks:
   - name: admin password change
     asa_config:
       lines:
          - "username {{ user_name }} password {{ user_pass }}"
   - name: user password change
     asa_config:
       lines:
          - "username {{ ruser_name }} password {{ ruser_pass }}"


- hosts: localhost
  gather_facts: false
  tasks:
  - name: remote login linux shell admin-exec
    expect:
      command: ssh -o StrictHostKeyChecking=no -l "{{ user_name }}" "{{ hostvars['ae0000-fw001']['ansible_host'] }}"
      responses:
        ".*[Pp]assword:.*": "{{ user_pass }}"
      timeout: 10
    changed_when: false

  - name: remote login linux shell user-exec
    expect:
      command: ssh -o StrictHostKeyChecking=no -l "{{ ruser_name }}" "{{ hostvars['ae0000-fw001']['ansible_host'] }}"
      responses:
        ".*[Pp]assword:.*": "{{ ruser_pass }}"
      timeout: 10
    changed_when: false


- hosts: ae0000-fw001
  gather_facts: false
  collections:
  - cisco.asa
  tasks:
   - name: config save
     asa_command:
        commands: 'write mem'