# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FileStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, size: int=None, mtime: datetime=None):  # noqa: E501
        """FileStatus - a model defined in Swagger

        :param name: The name of this FileStatus.  # noqa: E501
        :type name: str
        :param size: The size of this FileStatus.  # noqa: E501
        :type size: int
        :param mtime: The mtime of this FileStatus.  # noqa: E501
        :type mtime: datetime
        """
        self.swagger_types = {
            'name': str,
            'size': int,
            'mtime': datetime
        }

        self.attribute_map = {
            'name': 'name',
            'size': 'size',
            'mtime': 'mtime'
        }
        self._name = name
        self._size = size
        self._mtime = mtime

    @classmethod
    def from_dict(cls, dikt) -> 'FileStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The FileStatus of this FileStatus.  # noqa: E501
        :rtype: FileStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this FileStatus.

        ファイル名  # noqa: E501

        :return: The name of this FileStatus.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this FileStatus.

        ファイル名  # noqa: E501

        :param name: The name of this FileStatus.
        :type name: str
        """

        self._name = name

    @property
    def size(self) -> int:
        """Gets the size of this FileStatus.

        ファイルサイズ(バイト数)  # noqa: E501

        :return: The size of this FileStatus.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this FileStatus.

        ファイルサイズ(バイト数)  # noqa: E501

        :param size: The size of this FileStatus.
        :type size: int
        """

        self._size = size

    @property
    def mtime(self) -> datetime:
        """Gets the mtime of this FileStatus.

        最終更新日時  # noqa: E501

        :return: The mtime of this FileStatus.
        :rtype: datetime
        """
        return self._mtime

    @mtime.setter
    def mtime(self, mtime: datetime):
        """Sets the mtime of this FileStatus.

        最終更新日時  # noqa: E501

        :param mtime: The mtime of this FileStatus.
        :type mtime: datetime
        """

        self._mtime = mtime
