- name: admin password change
  no_log: true
  bigip_user:
    state: present
    username_credential: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password_credential: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    shell: tmsh
    provider:
      server: "{{ hostname }}"
      user: "{{ cs_obj.ansibleID }}"
      password: "{{ cs_obj.ansiblePassword }}"
      validate_certs: no
  vars:
    connection: local

- name: remote login linux shell admin-exec
  expect:
    command: ssh -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local

- name: config save
  bigip_config:
    save: yes
    provider: "{{ provider }}"
  vars:
    connection: local
