# vdom利用時修正が必要！
- name: "admin password change"
  raw: |
    config global
    config system admin
    edit "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    set password "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    set accprofile "super_admin"
    next
    end
    exit
  vars:
    ansible_network_os: fortinet.fortios

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local
