- name: update user
  ansible.netcommon.telnet:
    user: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}" 
    login_prompt: 'Username: '
    prompts:
      - "[>|#]|Password: "
    commands:
      - conf t
      - "username {{ cs_obj[loop_protocol ~ 'ID'] }} secret {{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  vars:
    ansible_connection: local

- name: update connection
  ansible.netcommon.telnet:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt: 'Username: '
    prompts:
      - "[>|#]|Password: "
    commands:
      - "!telnet login admin-exec"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local


- name: config save
  ansible.netcommon.telnet:
    user: "{{ cs_obj.ansibleID }}"
    password: "{{ cs_obj.ansiblePassword }}"
    login_prompt: 'Username: '
    prompts:
      - "[>|#]|Password: "
    commands:
      - write memory
    timeout: 10
  vars:
    ansible_connection: local
