- name: admin password change
  junos_user:
    name: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    role: super-user
    encrypted_password: "{{ cs_obj[loop_protocol ~ 'Password'] | password_hash('sha512') }}"
    state: present
  vars:
    ansible_connection: netconf
    ansible_network_os: junos
    ansible_ssh_port: 22

- name: remote login linux shell admin-exec
  expect:
    command: ssh -o StrictHostKeyChecking=no -l "{{ cs_obj[loop_protocol ~ 'ID'] }}" "{{ hostname }}"
    responses:
      ".*[Pp]assword:.*": "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    timeout: 10
  changed_when: false
  vars:
    ansible_connection: local
