- name: update connection
  ansible.netcommon.telnet_aoi:
    user: "{{ cs_obj[loop_protocol ~ 'ID'] }}"
    password: "{{ cs_obj[loop_protocol ~ 'Password'] }}"
    login_prompt:
      - "*Ver*"
    password_prompt:
      - "*login*"
    prompts:
      - ">"
    commands:
      - show username
      - "#telnet login admin-exec"
    timeout: 10

