---
- name: install packages
  apk:
    name:
    - postgresql
    - vim
    update_cache: true
- name: create postgresql directories
  file:
    path: "{{ item }}"
    state: directory
    owner: postgres
    group: postgres
    mode: 0755
  loop:
  - '/var/lib/postgresql/data'
  - '/run/postgresql'
- name: put files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
  - src: fastify
    dest: /root
  - src: docker-entrypoint.sh
    dest: /usr/local/bin
  - src: create-database.sh
    dest: /usr/local/bin
- name: put files from template
  template:
    src: vars.ts.j2
    dest: /root/fastify/src/vars.ts
    mode: 0755
- name: npm install
  npm:
    path: /root/fastify
- name: npm run build
  command:
    cmd: 'npm run build'
    chdir: /root/fastify

