---
- name: install tini
  apk:
    name:
    - tini
    update_cache: true
- name: pip install packages
  pip:
    name:
    - docker
    - flask
    - requests
    state: present
- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop:
  - '/root/.docker'
  - '/root/session-manager'
- name: put files
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0755
  loop:
  - src: docker-entrypoint.sh
    dest: /
  - src: access_guacamole_api.py
    dest: /root/session-manager
- name: put files from template
  template:
    src: main.py.j2
    dest: /root/session-manager/main.py
    mode: 0755
- name: create link to cacert
  file:
    src: /etc/ssl/certs/cacert.pem
    dest: /root/.docker/ca.pem
    state: link
