---
- import_role:
    name: python-aptk
- name: copy favicon
  copy:
    remote_src: false
    src: favicon-optage.ico
    dest: ./frontend/
  become: true
  become_method: su

- name: copy logo-appbar
  copy:
    remote_src: false
    src: logo-optage.png
    dest: ./frontend/
  become: true
  become_method: su
