---
- import_role:
    name: python-aptk
- name: ensures icons dir exists
  file: 
    path: "./icons"
    state: directory
- name: copy favicon
  copy:
    remote_src: false
    src: unirita_favicon.ico
    dest: ./icons/
  become: true
  become_method: su

- name: copy logo-appbar
  copy:
    remote_src: false
    src: unirita_logomark.png
    dest: ./icons/
  become: true
  become_method: su
